name: documentation

on: 
  push:
    branches:
        - 'main'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Fast-forward tag to latest commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          TAG_NAME="25.10"

          # Create or update the tag to point to HEAD
          git tag -f "$TAG_NAME"

          # Push the tag (forcefully to update it)
          git push origin "$TAG_NAME" --force
          
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme myst_parser
      - name: Sphinx build
        run: |
          cd doc
          mkdir _build
          python3 build_docs.py
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/_build/html
          force_orphan: true
